# Generated by Django 4.1 on 2022-08-27 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_contact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='email',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='mobile',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='remarks',
        ),
    ]
