# Generated by Django 4.1 on 2022-08-27 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_product_delete_contact'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
    ]
