# Generated by Django 4.1 on 2022-08-30 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_discount',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
