# Generated by Django 4.1 on 2022-09-14 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_reviews'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reviews',
            old_name='reviwes',
            new_name='reviews',
        ),
    ]
